---
label: Theme configuration
hide_body: false
fields:
- type: text
  name: huisproject
  description: welkom tekst
  hidden: false
  label: Banaan site
  config:
    min: 20
- type: textarea
  name: site_description
  label: Site description
- type: textarea
  name: hero_title
  label: Hero title
  config:
    wysiwyg: true
    schema:
      format: html
- type: textarea
  name: hero_subtitle
  label: Hero subtitle
  config:
    wysiwyg: true
    schema:
      format: html
- name: footer
  label: Footer text
  type: text
  hidden: false
  default: ''
  description: Oke <strong>voettekst</strong>
- type: boolean
  name: dark_mode
  label: Dark mode
  default: true
pages:
- data/theme.json
